musicas_A = [
    "A alegria está no coração",
    "A benção (Elevation Worship)",
    "A boa parte (FHOP)",
    "A começar em mim",
    "A Deus demos glória - O grande amor de Deus (hino 042)",
    "A história de Deus (Livres para adorar)",
    "A minh'alma está cheia de paz",
    "A paz do Senhor é o que nós queremos (Rebanhão)",
    "A Ti e só a Ti (Mosaic / Oitava Music)",
    "A Ti me entrego (Vineyard)",
    "A vitória é daquele que contemplar (Adhemar de Campos)",
    "Abra os olhos do meu coração (David Quinlan)",
    "Acendo o fogo em mim (Vineyard / Beto Tavares)",
    "Aclame ao Senhor (Diante do Trono)",
    "Acredito (Newsboys / Leonardo Gonçalves)",
    "Adorai em majestade",
    "Agrada-te do Senhor",
    "Águas purificadoras (Diante do Trono)",
    "Ainda que a figueira (Fernandinho)",
    "Ajuntamento (Jorge Camargo)",
    "Aleluia, salvação e glória",
    "Alfa e Ômega (Marine Friesen)",
    "Algo novo sempre acontece (Silvério Peres)",
    "Alto preço (Asaph Borba)",
    "Andam procurando a razão de viver",
    "Andou onde ando eu",
    "Ano do jubileu (Asaph Borba)",
    "Ao Deus de Abraão - Deus de Abraão (hino 021)",
    "Ao Deus de amor - Maravilhas divinas (hino 033)",
    "Ao nosso Deus que se assenta no trono",
    "Ao orarmos, Senhor",
    "Ao que é digno (Paulo Rogério)",
    "Ao que está assentado",
    "Ao único",
    "Aos pés da cruz (Kleber Lucas)",
    "Aquele que está com Cristo (Comunidade Evangélica Goiânia)",
    "Aquele que foi manifestado em carne",
    "Aquele que tem os meus mandamentos (Grupo Semente)",
    "Aquele que tem sede e busca",
    "Aqui viemos Te adorar, ó Cristo",
    "Arraial do povo de Deus (Daniel Souza)",
    "As trevas estremecem (Mosaic / Mariana Valadão)",
    "Atos 2 (Gabriela Rocha)",
    "Aumenta o fogo (Nívea Soares)",
    "Autor da minha fé (PC Baruk / Paulo Cézar)",
    "Avance e Vença (Oitava Music)"
]

musicas_B = [
    "Bem aventurado (Aline Barros)",
    "Bendito é o Rei (FHOP)",
    "Bendize, ó minhalma ao Senhor",
    "Bom estarmos aqui (Renascer Praise)",
    "Bom perfume (Gabi Sampaio)",
    "Bondade de Deus (Bethel / Pedras vivas)",
    "Buscai primeiro o Reino de Deus"
]

musicas_C = [
    "Cada estrada em que eu andei",
    "Cada instante contigo, Senhor",
    "Caiam por terra agora",
    "Caminho de milagres (Aline Barros)",
    "Caminho no deserto (Viva Adoração)",
    "Canção ao Cordeiro (Gabriel Guedes e Israel Salazar)",
    "Canção da alvorada (João Alexandre)",
    "Canção do Apocalipse (Diante do Trono)",
    "Canção eterna (FHOP)",
    "Cantai, pois a vitória é ganha",
    "Cantarei Teu amor",
    "Carvalhos de justiça (Josué Rodrigues)",
    "Casa de benção (Eyshila)",
    "Castelo Forte (hino 155)",
    "Cego de Jericó",
    "Ceifeiros da seara santa - Ceifeiros do Senhor (hino 318)",
    "Celebrai a Cristo, celebrai",
    "Celebrai com júbilo ao Senhor",
    "Celebremos com danças ao nosso Deus",
    "Cheguemo-nos pois com ousadia",
    "Chuvas de bençãos (hino 172)",
    "Clamo a Ti",
    "Clamo Jesus (PC Baruk e Marsena)",
    "Colossenses e Suas linhas de amor (FHOP e Marco Telles)",
    "Com Cristo unido - Unido com Cristo (hino 115)",
    "Com muito louvor (Cassiane)",
    "Como é precioso (Asaph Borba)",
    "Como suspira a corça",
    "Comunhão (Gabi Sampaio)",
    "Comunhão (Kleber Lucas)",
    "Conheci um grande amigo (Rebanhão)",
    "Consagração / Louvor ao Rei (Aline Barros)",
    "Coração igual ao Teu (Diante do Trono)",
    "Corpo e família (Daniel Souza)",
    "Correrei (Samuel Mizhahy)",
    "Custe o que custar (Samuel Aleixo, Isa Izaú / Oitava Music)"
]

musicas_D = [
    "De todas as tribos (Guilherme Kerr)",
    "Declaramos (Daniel Souza)",
    "Descansarei (Comunidade Evangélica Maringá)",
    "Descerá sobre Ti (Comunidade Evangélica Nilópolis)",
    "Desde o princípio de todas as coisas",
    "Desde os confins da Terra (Igreja Bíblica da Paz)",
    "Desejo do meu coração (Trazendo a Arca)",
    "Deus cuida de mim (Kleber Lucas)",
    "Deus de maravilhas (Christine D´Clario)",
    "Deus de promessas (Trazendo a Arca)",
    "Deus do impossivel (Ministério Apascentar)",
    "Deus dos Antigos (hino 018)",
    "Deus é Deus (Delino Marçal)",
    "Deus está aqui",
    "Deus está no templo - Culto à Trindade (hino 004)",
    "Diante da cruz (Aline Barros)",
    "Diante de Ti",
    "Digno de tudo (Gabi Sampaio)",
    "Digno é o Senhor (Aline Barros)",
    "Dignos És de glória",
    "Disseste (Clamor pelas nações)",
    "Do norte vem o áureo esplendor (Expresso Luz)",
    "Doce nome (Vencedores por Cristo)",
    "Dominio e poder",
    "Dono das estrelas (Trazendo a Arca)",
    "Dou graças de coração",
    "Doxologia (hino 006)"
]

musicas_E = [
    "E dizemos amém (Lakewood Music)",
    "Egito (Bethel / Isaias Saas)",
    "Eis dos anjos a harmonia - Louvor Angelical (hino 240)",
    "Ele é exaltado (Comunidade Evangélica RJ)",
    "Ele é o leão da tribo de Judá",
    "Em espírito (Arieta Magrini)",
    "Em memória de Ti (Aristeu Pires Júnior)",
    "Em nome de Jesus (Israel & New Bread)",
    "Em nome do Senhor Jesus",
    "Enche este lugar (David Quinlan)",
    "Enche Tua casa",
    "Enche-me, Espírito (Benedito Carlos e Alda Célia)",
    "Enquanto eu calei",
    "Enquanto eu respirar (Adoração & Adoradores)",
    "Então se verá o Filho do homem",
    "Entre a fé e a razão (Trazendo a Arca)",
    "Entrega (Vineyard e Heloisa Rosa)",
    "Ergo as minhas mãos",
    "És a nossa estrela da manhã",
    "És a razão do meu viver",
    "Esperei confiantemente no Senhor",
    "Espírito Santo de Deus",
    "Espírito, enche a minha vida",
    "Essência da adoração (David Quinlan)",
    "Estamos de pé (Marcus Salles)",
    "Estamos reunidos aqui, Senhor",
    "Este é o dia",
    "Este é o meu respirar",
    "Este reino (Hillsong / Ana Paula Valadão)",
    "Eterna Graça (Samuel Aleixo, Davi Frossard / Oitava Music)",
    "Eterno Pai, Teu povo congregado - A Igreja em adoração (hino 003)",
    "Eu celebrarei cantando ao Senhor",
    "Eu creio (Gabriela Rocha)",
    "Eu creio que tudo é possível",
    "Eu creio, Senhor, na divina promessa - Necessidade (hino 068)",
    "Eu e minha casa (André Valadão)",
    "Eu me alegro em Ti (Hillsong Worship / Ministério Shalom)",
    "Eu me rendo (Renascer Praise)",
    "Eu navegarei",
    "Eu posso escutar o exército de Deus",
    "Eu quero é Deus (Comunidade Evangélica Nilópolis)",
    "Eu quero ser, Senhor amado (Vaso novo)",
    "Eu só quero estar onde estás",
    "Eu sou Teu (Jesus Culture / Gabriela Rocha)",
    "Eu te amo, ó Deus",
    "Eu te louvarei meu bom Jesus (Ronaldo Bezerra)",
    "Eu te louvarei Senhor de todo o meu coração",
    "Eu vejo a glória",
    "Eu vou construir (Pat Barrett / Nívea Soares)",
    "Eu vou passar pela cruz (PG)",
    "Eu vou viver uma virada (Ministério Apascentar)",
    "Exaltai (Igreja Bíblica da Paz)",
    "Exaltar-Te-ei (Vencedores por Cristo)"
]

musicas_F = [
    "Farás outra vez (Elevation Worship / Marcos Freire)",
    "Favor de Deus (Discopraise)",
    "Faz chover (Fernandinho)",
    "Fiel a mim (Eyshila)",
    "Filho de Davi (David Quinlan)",
    "Filho do Deus vivo (Nívea Soares)",
    "Finda-se este dia - Oração noturna (hino 148)",
    "Firme nas promessas (hino 077)",
    "Flua em mim, Senhor",
    "Formoso És",
    "Fortalece a Tua Igreja - Renovação (hino 299)"
]

musicas_G = [
    "Galhos secos",
    "Galileu (Fernandinho)",
    "Geração eleita (Joe Vasconcelos)",
    "Geração que dança (David Quinlan)",
    "Glória pra sempre ao Cordeiro de Deus (Vencedores por Cristo)",
    "Glorioso És (BJ Putnam)",
    "Graça (Israel Salazar)",
    "Graças te dou por tudo - Hino de gratidão (hino 062)",
    "Grande Deus (Diante do Trono)",
    "Grande Deus (Trazendo a Arca)",
    "Grande é o Senhor (Adhemar de Campos)",
    "Grandes coisas (Fernandinho)",
    "Gratidão (FHOP)",
    "Gratidão (Cristo Vivo)",
    "Grato sou (Elevation Worship / Lagoinha Worship)"
]

musicas_H = [
    "Há um Doce Espírito aqui",
    "Há um só corpo, um só Senhor",
    "Há unção de Deus neste lugar",
    "Habito no abrigo (Trazendo a Arca)",
    "Hino da vitória (Cassiane / Gabriela Rocha)",
    "Hoje é tempo de louvar a Deus",
    "Hoje eu vou tocar nas vestes de Jesus",
    "Homem de guerra (Adhemar de Campos)",
    "Honra e louvores (Ron Kenoly / PC Baruk / Oitava Igreja)",
    "Hosana (Hillsong / Mariana Valadão)"
]

musicas_I = [
    "Igreja (Renascer Praise)",
    "Infinitamente mais (Asaph Borba)"
]

musicas_J = [
    "Já ouviste a minha voz (Vineyard)",
    "Jeová é o Teu cavaleiro",
    "Jeová Jireh (Aline Barros)",
    "Jesus (Chris Tomlin)",
    "Jesus Cristo mudou meu viver (Aline Barros)",
    "Jesus é a aliança",
    "Jesus é o centro (Israel & New Bread / Davi Sacer)",
    "Jesus é o Rei da glória (Daniel Souza)",
    "Jesus em Tua presença (Asaph Borba / Morada)",
    "Jesus És o meu amado (Diante do Trono)",
    "Jesus prevaleceu (Daniel Souza)",
    "Jesus te entronizamos",
    "Jesus, nome dos nomes",
    "Jesus, o plano perfeito (Renascer Praise)",
    "Jesus, seja o centro (Vineyard)"
]

musicas_K = [
    "Laços de amor (Vineyard / Oitava Igreja)",
    "Leão (Gabriela Rocha)",
    "Leão (Elevation Worship / Thalles Roberto)",
    "Leva-me além (Trazendo a Arca)",
    "Libera Tua unção",
    "Liberdade (Livres para adorar)",
    "Lion and the Lamb (Bethel / Marcus Salles)",
    "Logo de manhã quero Te buscar",
    "Louvamos-Te ó Deus - Louvor e glória (hino 047)",
    "Louvemos ao Senhor / Magnifiquemos / Cristo é a nossa vida (Adhemar de Campos)",
    "Lugar Secreto (Gabriela Rocha)",
    "Lugar seguro (Aline Barros)"
]

musicas_M = [
    "Magnificar",
    "Mais amor, mais poder",
    "Mais de Ti (Mosaic / Oitava Music)",
    "Mais do que milhares é Cristo - Linda Melodia (hino 104)",
    "Mais do que tudo (Vineyard Piratininga)",
    "Mais forte que a morte (Livres para adorar)",
    "Mais perto quero estar - União com Deus (hino 116)",
    "Mais que uma voz (PC Baruk)",
    "Majestade (Livres para adorar)",
    "Manancial (Aline Barros)",
    "Maranata (Ministério Avivah)",
    "Maranata (Pedro Cabral)",
    "Maravilhosa e Eterna Graça (Oitava Music)",
    "Marca da promessa (Trazendo a Arca)",
    "Marca de Cristo (Comunidade Evangélica Internacional Zona Sul)",
    "Me atraiu (Gabriela Rocha)",
    "Me derramar (Vineyard)",
    "Mestre o mar se revolta - Sossegai (hino 254)",
    "Meu alvo (Kleber Lucas)",
    "Meu maior amor (Nívea Soares)",
    "Meu Senhor, sou Teu - Mais perto da cruz (hino 222)",
    "Meu universo (PG)",
    "Mil vezes mil louvores - Louvores sem fim (hino 038)",
    "Minha pátria para Cristo - Petição pela Pátria (hino 379)",
    "Minha vida entrego a Ti",
    "Minh'alma engrandece ao Senhor (Asaph Borba)",
    "Minhas guerras (Brasa Church)",
    "Moisés / Cântico à Moisés (Fernandinho)"
]

musicas_N = [
"Na corte do Egito (Trazendo a arca)",
    "Na Terra como no céu (Gabi Sampaio e Weslei Santos)",
    "Nada além do sangue (Fernandinho)",
    "Nada é impossível (Nothing is impossible) (Planetshakers/4por 1)",
    "Não a nós, Senhor",
    "Não há amor igual (Morada)",
    "Não há impossível para Deus",
    "Não há outro (PC Baruk)",
    "Não há um nome igual (No other name) (Hillsong Worship/Ministério Avivah)",
    "Não olho as circunstâncias",
    "Não seremos abalados (We will not be shaken) (Bethel/Nívea Soares)",
    "Não temerei (Heloísa Rosa)",
    "Não tenha sobre TI",
    "Não vou calar meus lábios",
    "Nas estrelas",
    "Nasce Jesus (hino 239)",
    "Ninguém explica Deus (Preto no Branco, Gabriela Rocha)",
    "No arraial do povo de Deus (Daniel Souza)",
    "No controle (Vineyard)",
    "Noite de Paz (hino 243)",
    "Nós somos o povo a quem Deus libertou",
    "Nos últimos dias será abundante a justiça",
    "Nosso Comandante (Adhemar de Campos)",
    "Nosso Deus (Gui Rebustini)",
    "Nosso Deus é soberano",
    "Nosso general (Adhemar de Campos)",
    "Nova criatura (Kleber Lucas)",
    "Novo coração"
    ]

musicas_O = [
"O caminho de Deus é perfeito",
    "O céu é o meu lugar (Samuel Aleixo, Sarah Lanza/Oltava Music)",
    "O Espírito de Deus está aqui (Arianne)",
    "O Leão da tribo de Judá (Adhemar de Campos)",
    "O mesmo Deus (Same God) (Elevation Worship e Jonsal Barrientes)",
    "O meu cálice elevo a TI, Senhor",
    "O meu louvor é fruto",
    "O nome de Jesus (Adhemar de Campos)",
    "O poderoso (You are Mighty) (Craig Musseau)",
    "Ó quão preciosa e rica promessa - Segurança do Crente (hino 146)",
    "O que seria de mim (Rodrigo Areal/Oltava Music)",
    "O que Sua glória fez comigo (Fernanda Brum)",
    "O Rei (Aline Barros)",
    "O Rei da glória",
    "Ó Rei sublime - Rei sublime (hino 019)",
    "O Senhor é a minha força",
    "O Senhor é a minha luz",
    "O Senhor é bom (Nivea Soares)",
    "O Senhor está levantando um grande exército (Koinonya)",
    "O Vencedor (Gateway Worship e Juliano Son)",
    "Ó vinde crentes dar louvor - Exaltação e louvor (hino 039)",
    "Ó vinde fiéis, triunfantes e alegres - Adoração (hino 230)",
    "Oceanos (Hillsong)",
    "Oferta de amor (Koinonya)",
    "Oh quão lindo esse nome é (Hillsong)",
    "Os anjos de Deus vieram a nós",
    "Os anjos te louvam (Eli Soares)",
    "Os reis da Terra se prostrarão",
    "Os sonhos de Deus (Ludmila Ferber)",
    "Os sonhos de Deus (Nani Azevedo)",
    "Ouga o tremor (Filhos do homem/Bethel)",
    "Ousado amor (Cory Asbury/Isaías Saad)",
    "Ouve, ó Deus, o meu clamor",
    "Ouve-se o júbilo de todos os povos",
    "Ouvir o Teu falar (Discopraise)"
]

musicas_P = [
"Pai de amor gosto tanto de Ti (Vencedores por Cristo)",
    "Pai de luz (Father of lights) (Vineyard)",
    "Pai eu quero contemplar",
    "Pai eu te amo",
    "Pai nosso (Our Father) (Bethel/ Leonardo Gonçalves e Lucimare)",
    "Pai, Tu És santo (You are still Holy) (Vineyard)",
    "Pão da vida (Cláudio Claro)",
    "Perdão (Daniel Souza)",
    "Peregrinando por sobre os montes - Brilho Celeste (hino 114)",
    "Poder do Teu amor (Diante do Trono)",
    "Poder pra salvar (Aline Barros)",
    "Poderoso Deus (Antonio Cirilo)",
    "Põe Tua mão na mão do meu Senhor",
    "Porque Ele vive",
    "Povo justificado (Daniel Souza)",
    "Pra sempre (Livres para adorar)",
    "Pra sempre (Forever) (Min. Avivah)",
    "Pra sempre Teu (Gateway Worship)",
    "Praise (Louve)/Adore (Videira Music)",
    "Preciosas são as horas - Comunhão preciosa (hino 128)",
    "Preciso de Ti (Diante do Trono/Amém e Julliany Sousa)",
    "Primeiro amor (Carlinhos Félix)",
    "Proclamarei (Davi Smith/Oltava Music)",
    "Promessas (Promises) (Sarah Beatriz e Samuel Messias)"
]

musicas_Q = [
"Quando a alma sequiosa - Vencendo vem Jesus (hino 147)",
    "Quando entro em Tua presença (Igreja Bíblica da Paz)",
    "Quando eu te adoro",
    "Quando lá dos céus descendo - A chamada final (hino 297)",
    "Quanto amor (Massao Sugulhara/PC Baruk)",
    "Quão formoso És",
    "Quão grande é o Meu Deus (Soraya Moraes)",
    "Que segurança tenho em Jesus - Segurança e alegria (hino 144)",
    "Quebra as cadeias (Daniel Souza)",
    "Quebrantado (Vineyard)",
    "Quem dizes que eu sou (Who you say I am) (Hillsong Worship)",
    "Quem é Deus acima do Senhor",
    "Quem nos separará",
    "Quem pode livrar como o Senhor",
    "Quem sou eu? (PG)",
    "Quero louvar-Te",
    "Quero que valorize",
    "Quero sempre estar (Tua unção) (Min. Nova Jerusalém)",
    "Quero Te adorar, ó Rei Jesus",
    "Quero voltar ao início de tudo (Rebanhão)"
]

musicas_R = [
"Raise a Hallelujah (Bethel/Ottava Igreja)",
    "Recebi um novo coração do Pai (Daniel Souza)",
    "Rei das nações (Vencedores por Cristo)",
    "Rei de glória (Rey de gloria) (Christine D’Clario)",
    "Rei de majestade (King os majesty) (Hillsong United)",
    "Rei meu (Aline Barros)",
    "Reina (PC Baruk)",
    "Reina em mim (Vineyard)",
    "Reina o Senhor, treinam os povos",
    "Rendido estou (Aline Barros e Fernandoinho)",
    "Renova-me",
    "Renova-me, Senhor Jesus",
    "Ressuscita-me (Aline Barros)",
    "Rocha eterna (hino 136)",
    "Rompendo em fé (Com. Ev. Int. Zona Sul)",
    "Rude cruz (hino 266)"
]

musicas_S = [
"Salmo 19 (Vineyard)",
    "Salmo 57 (Sarah Lanza/Oitava Music)",
    "Salmo 96",
    "Santo (Vineyard)",
    "Santo (Louvem) (Renascer Praise)",
    "Santo e ungido (Vineyard)",
    "Santo Espírito (PC Baruk e Leonardo Gonçalves)",
    "Santo pra sempre (Gabriel Guedes)",
    "Santo! Santo! Santo! - Trindade santíssima (hino 011)",
    "Santo, Pai Tu És santo (Clamor pelas nações)",
    "Saudai o nome de Jesus - Glória e coroação (hino 052)",
    "Saudai o Rei Jesus (Bethe! Music/Viva adoração)",
    "Se confessarmos os nossos pecados",
    "Se da vida as vagas - As muitas bençãos (hino 063)",
    "Se eu me humilhar (Discopraise)",
    "Se não for pra te adorar (Fernandoinho)",
    "Se paz a mais doce - Aflição e paz (hino 108)",
    "Seguro estou, não tenho temor - Refúgio verdadeiro (hino 145)",
    "Sei que o melhor amigo é Cristo - O melhor amigo (hino 161)",
    "Seja bendito o Cordeiro - Pureza no sangue de Cristo (hino 269)",
    "Seja engrandecido",
    "Seja louvado o Deus supremo - Deus seja louvado (hino 017)",
    "Seja o centro (Vineyard)",
    "Seja o meu canto (Vencedores por Cristo)",
    "Seja tudo em mim (Gabi Sampaio)",
    "Sempre vencendo (hino 049)",
    "Senhor da criação (Vineyard)",
    "Senhor e Rei (Trazendo a arca)",
    "Senhor Formoso És (Marcos Góes)",
    "Senhor meu Deus, quando eu - Ao Deus grandioso (hino 026)",
    "Senhor Tu tens sido",
    "Senhor, eu preciso (PC Baruk)",
    "Senhor, formoso És",
    "Senhor, Te amo eternamente",
    "Senhor, Te quero (Vineyard)",
    "Serás sempre Deus (Trazendo a arca)",
    "Seu maravilhoso olhar",
    "Seu nome é (Daniel Souza)",
    "Seu sangue (Fernandoinho)",
    "Sim eu sei Senhor que Tu És soberano",
    "Sim, sofrimentos te causei - Perdão (hino 071)",
    "Sinceramente eu preciso encontrar (Vencedores por Cristo)",
    "Só o poder de Deus (Vencedores por Cristo)",
    "Só Tu és Santo (Morada)",
    "Soberano (Samuel Mizhahy)",
    "Sobre as águas (Trazendo a arca)",
    "Somente ponho a minha fé - Firmeza na fé (hino 093)",
    "Somos jovens num mundo velho - Mocidade presbiteriana (hino 382)",
    "Sonda-me, ó Deus - Coração quebrantado (hino 067)",
    "Sonda-me, usa-me (Aline Barros)",
    "Sopra em mim sopro de Deus",
    "Sou forasteiro aqui - A mensagem real (hino 288)",
    "Sua bandeira sobre mim (David Quinlan)",
    "Sua justiça prevalecerá (Nivea Soares)"
]

musicas_T = [
"Te agradeço (Kleber Lucas)",
    "Te agradeço (Diante do Trono)",
    "Te exaltamos ó Cordeiro Santo",
    "Te louvamos ó Senhor",
    "Te louvo (We praise You) (Bethel Music/Marcus Salles)",
    "Tendo Deus outrora falado (Vencedores por Cristo)",
    "Terremoto (Eyshila)",
    "Tetelestai (Ana Christine, Davi Frossard/Oltava Music)",
    "Teu amor não falha (Nivea Soares)",
    "Teu poder (Famous for) (Tauren Wells/Gui Baptista)",
    "Teu reino (Cristo Vivo)",
    "Teu toque (Gabi Sampaio e Nivea Soares)",
    "Teus altares",
    "Toda sorte de bençãos (Trazendo a arca)",
    "Todavia me alegrarei (Samuel Messias)",
    "Todo som (Banda Resgate)",
    "Todos que tem sede (Vineyard)",
    "Tributo a Yehovah (Adhemar de Campos)",
    "Tu és + Aguas Purificadoras (FHOP)",
    "Tu És bom (Lakewood Music/Adoração & Adoradores)",
    "Tu és digno do meu louvor (Vineyard Piratininga)",
    "Tu és fiel, Senhor - O Deus fiel (hino 032)",
    "Tu És maior (Joe Vasconcelos)",
    "Tu És santo (Ronaldo Bezerra)",
    "Tu És soberano",
    "Tu És tremendo, Deus (Mariana Valadão e Ana Paula Valadão)",
    "Tu estás assentado no trono",
    "Tu vives entre os querubins (Beto Tavares)",
    "Tua graça me basta (Trazendo a arca)",
    "Tua graça me basta (Vineyard)",
    "Tua Igreja Canta (Israel Salazar)",
    "Tua misericordia",
    "Tua Senhor é a força (Koinonya)",
    "Tuas obras te coroam - Coroação (hino 028)",
    "Tudo é diferente (Aline Barros)",
    "Tudo posso em Deus (Davi Sacer)"
]

musicas_U = [
"Um ano mais de vida - Graças pelo aniversário (hino 396)",
    "Um chamado (4 po 1)",
    "Uma nova história (Fernandoinho)",
    "Único (FHOP)"
]

musicas_V = [
"Vamos adorar a Deus",
    "Vamos nós louvar a Deus - Louvor (hino 014)",
    "Vasos quebrados (Broken Vessels) (Hillsong Worship/Marine Friesen)",
    "Vem com Josué",
    "Vem de Ti, Senhor (Diante do Trono)",
    "Vem derrama a paz (Koinonya)",
    "Vem neste lugar",
    "Vem sobre mim (Fall on me) (Vineyard)",
    "Vem visita Tua Igreja",
    "Vem, esta é a hora (Vineyard)",
    "Venha o Teu reino (Davi Sacer)",
    "Venho, Senhor, minha vida oferecer",
    "Ventos de avivamento (Com. Ev. Zona Sul)",
    "Vida aos sepulcros (Elevation Worship)",
    "Vim para adorar-Te",
    "Vitória no deserto (Aline Barros)",
    "Vitorioso És (Victory is yours) (Bethel)",
    "Volte os olhos pra Jesus",
    "Vós criaturas de Deus Pai - A criação e Seu Criador (hino 010)",
    "Vou crer (André Valadão)"
]

REPERTORIO = (
    musicas_A + 
    musicas_B +
    musicas_C +
    musicas_D +
    musicas_E +
    musicas_F +
    musicas_G +
    musicas_H +
    musicas_I +
    musicas_J +
    musicas_K +
    musicas_M +
    musicas_N +
    musicas_O +
    musicas_P +
    musicas_Q +
    musicas_R +
    musicas_S +
    musicas_T +
    musicas_U +
    musicas_V
    );